name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-analyze:
    name: Test and Analyze
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    permissions:
      security-events: write
    steps:
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin

      - name: Cache Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-repository-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-repository

      - name: Cache Maven Wrapper (spring-petclinic)
        uses: actions/cache@v2
        with:
          path: ./spring-petclinic/.mvn/wrapper/maven-wrapper.jar
          key: ${{ runner.os }}-maven-wrapper-${{ hashFiles('./spring-petclinic/.mvn/wrapper/maven-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-spring-petclinic-maven-wrapper

      - uses: actions/checkout@v2

      - name: Build and Run Contrast Scan
        run: ./mvnw --batch-mode verify
        env:
          CONTRAST__API__URL: ${{ secrets.CONTRAST__API__URL }}
          CONTRAST__API__ORGANIZATION_ID: ${{ secrets.CONTRAST__API__ORGANIZATION_ID }}
          CONTRAST__API__USER_NAME: ${{ secrets.CONTRAST__API__USER_NAME }}
          CONTRAST__API__API_KEY: ${{ secrets.CONTRAST__API__API_KEY }}
          CONTRAST__API__SERVICE_KEY: ${{ secrets.CONTRAST__API__SERVICE_KEY }}

      - name: Upload Contrast Scan Results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: target/contrast-scan-reports/contrast-scan-results.sarif.json
          
          
          
        
  contrast-oss:
    name: Contrast OSS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm install
      - run: npm install -g @contrast/contrast-cli
      
      - run: contrast-cli --api_key $CONTRAST_API_KEY --authorization $CONTRAST_AUTHORIZATION --organization_id $CONTRAST_ORG_ID --host $CONTRAST_HOST --application_id $CONTRAST_APPLICATION_ID --language $LANGUAGE
        name: Contrast OSS Submit
        env:
          CONTRAST_API_KEY: ${{ secrets.CONTRAST__API__API_KEY }}
          CONTRAST_AUTHORIZATION: ${{ secrets.CONTRAST_AUTHORIZATION_HEADER }}
          CONTRAST_ORG_ID: ${{ secrets.CONTRAST__API__ORGANIZATION_ID }}
          CONTRAST_HOST: ${{ secrets.CONTRAST__API__URL }}
          CONTRAST_APPLICATION_ID: ${{ secrets.CONTRAST_APPLICATION_ID }}
          LANGUAGE: "JAVA"
          
      - run: contrast-cli -r -f -s high --silent --api_key $CONTRAST_API_KEY --authorization $CONTRAST_AUTHORIZATION --organization_id $CONTRAST_ORG_ID --host $CONTRAST_HOST --application_id $CONTRAST_APPLICATION_ID --language $LANGUAGE
        name: Contrast OSS Check
        env:
          CONTRAST_API_KEY: ${{ secrets.CONTRAST__API__API_KEY }}
          CONTRAST_AUTHORIZATION: ${{ secrets.CONTRAST_AUTHORIZATION_HEADER }}
          CONTRAST_ORG_ID: ${{ secrets.CONTRAST__API__ORGANIZATION_ID }}
          CONTRAST_HOST: ${{ secrets.CONTRAST__API__URL }}
          CONTRAST_APPLICATION_ID: ${{ secrets.CONTRAST_APPLICATION_ID }}
          LANGUAGE: "JAVA"          
